apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          # Use Never to ensure Kubernetes uses the local image built with Minikube
          # instead of trying to pull it from a remote registry (e.g., Docker Hub)
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -Dlogback.configurationFile=/etc/config/logback.xml
          volumeMounts:
            - name: logback-config
              mountPath: /etc/config
              readOnly: true
      volumes:
        - name: logback-config
          configMap:
            name: {{ .Chart.Name }}-config
            items:
              - key: logback.xml
                path: logback.xml