image:
  repository: api
  tag: latest
service:
  port: 3000
  targetPort: 3000

mongodb:
  image:
    repository: mongo
    tag: "8.2"
    pullPolicy: IfNotPresent
  service:
    port: 27017
  storage: 5Gi
  auth:
    secretName: mongodb-auth
    username: ""
    password: ""
    usernameKey: username
    passwordKey: password
